# DO NOT EDIT THIS FILE!
#
# Python module DCM__POA generated by omniidl

import omniORB
omniORB.updateModule("DCM__POA")

# ** 1. Stub files contributing to this module
import DCM_idl

# ** 2. Sub-modules

# ** 3. End
