# DO NOT EDIT THIS FILE!
#
# Python module DCM generated by omniidl

import omniORB
omniORB.updateModule("DCM")

# ** 1. Stub files contributing to this module
import DCM_idl
import DCM_Types_idl

# ** 2. Sub-modules

# ** 3. End
